name: PR Actions

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add GITHUB_SHORT_SHA env property with commit short sha
        run: echo "GITHUB_SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm run compile
        env:
          KEY_BSC_TEST: ${{ secrets.FAKE_CHAIN_PRIVATE_KEY }}
          KEY_BSC_MAINNET: ${{ secrets.FAKE_CHAIN_PRIVATE_KEY }}
